spring.application.name=SpringOathProject
spring.security.oauth2.client.registration.github.client-id=Ov23li24nMfYIHdkZWDN
spring.security.oauth2.client.registration.github.client-secret=2895ffc54e6aa57b2e409508904a795b26192eee
spring.security.oauth2.client.registration.github.scope=user:email,gist
