spring.application.name=SpringFileProjectFinal
spring.datasource.url=jdbc:postgresql://localhost:5432/springprojektfiles
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.security.oauth2.client.registration.github.client-id=Ov23li24nMfYIHdkZWDN
spring.security.oauth2.client.registration.github.client-secret=56a20f953e49086d923f3ec5b82fa3936b404d58
spring.security.oauth2.client.registration.github.scope=user:email,read:user
#spring.security.oauth2.client.registration.github.redirect-uri:http://localhost:8080/login/oauth2/code/github


